# Please run the codes below if you haven't installed required libraries
update.packages("ggplot2")
packageDescription("ggplot2")["Version"]
install.packages("ggplot2",type="source")
install.packages("plotly")
install.packages("raster")
install.packages("RColorBrewer")
install.packages("tidyverse")
install.packages("hrbrthemes")
install.packages("viridis")

# import library

library(plotly)
library(ggplot2)
library(gplots)
library(raster)
library(RColorBrewer)
library(tidyverse)
library(hrbrthemes)
library(viridis)

getwd()
setwd("/Users/USERNAME/PATH/data_scat32_analysis")
dir()

#F/A value vector formulation
pixel <- function(datatable) {
  t2 <- NULL
  
  for (i in 1:400)
  {
    t2 <- append(t2, datatable[,i])
  }# making a single dimension vector which contains value (ratio of Fret/Amcyan (F/A)) in each pixel
  return(t2)
}


# This is the data analysis for the mice transplanted with Scat3.2 with or without chemotherapy treatment 

#data import: importing the ratiometry data generated by ImageJ 

NT_3_1 <- read.table(file="Result of NT_3_1_on_G2.txt", header=F, sep="\t")
NT_3_2 <- read.table(file="Result of NT_3_2_on_G2.txt", header=F, sep="\t")
NT_4_1 <- read.table(file="Result of NT_4_1_on_G2.txt", header=F, sep="\t")
NT_4_5 <- read.table(file="Result of NT_4_5_on_G2.txt", header=F, sep="\t")
NT_6_2 <- read.table(file="Result of NT_6_2_on_G2.txt", header=F, sep="\t")
NT_2_3_6_2 <- read.table(file="Result of NT2_3_6_2_G2.txt", header=F, sep="\t")
NT_2_3_7_1 <- read.table(file="Result of NT2_3_7_1_G2.txt", header=F, sep="\t")
NT_2_3_7_2 <- read.table(file="Result of NT2_3_7_2_G2.txt", header=F, sep="\t")
NT_2_4_5_1 <- read.table(file="Result of NT2_4_5_1_G2.txt", header=F, sep="\t")
NT_2_4_6_3 <- read.table(file="Result of NT2_4_6_3_G2.txt", header=F, sep="\t")

T_3_3 <- read.table(file="Result of T_3_3_on_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_3_6 <- read.table(file="Result of T_3_6_on_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_4_1 <- read.table(file="Result of T_4_1_on_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_4_7 <- read.table(file="Result of T_4_7_on_G2_2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_6_4 <- read.table(file="Result of T_6_4_on_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_2_4_6_2 <- read.table(file="Result of T2_4_6_2_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_2_4_6_3 <- read.table(file="Result of T2_4_6_3_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_2_5_1 <- read.table(file="Result of T2_5_1_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_2_5_2 <- read.table(file="Result of T2_5_2_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7
T_2_5_5<- read.table(file="Result of T2_5_5_G2.txt", header=F, sep="\t") #this label is 5-5 but it is acutually R4_7


#######  heatmap formation (Fig S4E) ######

par(mfrow=c(1,2))
#heatmap for a visual field from a non treated mouse

t <- NT_4_5
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap for a visual field from a treated mouse 
t <- T_4_7
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot


###### density plot for intensity of F/A valuse ######

#summay vector formation and sorting 

NT31 <- sort(pixel(NT_3_1),decreasing=TRUE)
NT32 <- sort(pixel(NT_3_2),decreasing=TRUE)
NT41 <- sort(pixel(NT_4_1),decreasing=TRUE)
NT45 <- sort(pixel(NT_4_5),decreasing=TRUE)
NT62 <- sort(pixel(NT_6_2),decreasing=TRUE)
NT2362 <- sort(pixel(NT_2_3_6_2),decreasing=TRUE)
NT2371 <- sort(pixel(NT_2_3_7_1),decreasing=TRUE)
NT2372 <- sort(pixel(NT_2_3_7_2),decreasing=TRUE)
NT2451 <- sort(pixel(NT_2_4_5_1),decreasing=TRUE)
NT2463 <- sort(pixel(NT_2_4_6_3),decreasing=TRUE)

T33 <- sort(pixel(T_3_3),decreasing=TRUE)
T36 <- sort(pixel(T_3_6),decreasing=TRUE)
T41 <- sort(pixel(T_4_1),decreasing=TRUE)
T47 <- sort(pixel(T_4_7),decreasing=TRUE)
T64 <- sort(pixel(T_6_4),decreasing=TRUE)
T2462 <- sort(pixel(T_2_4_6_2),decreasing=TRUE)
T2463 <- sort(pixel(T_2_4_6_3),decreasing=TRUE)
T251 <- sort(pixel(T_2_5_1),decreasing=TRUE)
T252 <- sort(pixel(T_2_5_2),decreasing=TRUE)
T255 <- sort(pixel(T_2_5_5),decreasing=TRUE)

dev.off()

#density plot
plot(0, 0, type="n", xlim=c(0,6), ylim=c(0, 1.5), xlab="Fret signal(mVenus/Amcyan)", ylab="Density")
lines(density(NT31), col="blue")
lines(density(NT32), col="blue")
lines(density(NT41), col="blue")
lines(density(NT45), col="blue")
lines(density(NT62), col="blue")
lines(density(NT2362), col="blue")
lines(density(NT2371), col="blue")
lines(density(NT2372), col="blue")
lines(density(NT2451), col="blue")
lines(density(NT2463), col="blue")
lines(density(T33), col="red")
lines(density(T36), col="red")
lines(density(T41), col="red")
lines(density(T47), col="red")
lines(density(T64), col="red")
lines(density(T2462), col="red")
lines(density(T2463), col="red")
lines(density(T251), col="red")
lines(density(T252), col="red")
lines(density(T255), col="red")

###### formation of summary data for box plot and statistical analysis ######

# formation of  total summary data 

NT_total <- NULL
NT_total <- c(NT31, NT32, NT41,NT45,NT62,NT2362, NT2371, NT2372,NT2451,NT2463)
length(NT_total)
NT_total <- sort(NT_total,decreasing=TRUE)

T_total <- NULL
T_total <- c(T33,T36, T41,T47,T64,T2462,T2463,T251, T252, T255)
length(T_total)
T_total <- sort(T_total,decreasing=TRUE)

dev.off()

# box plot visulalization
# remove inf value
NT_t <- NT_total[!is.infinite(NT_total)]
T_t <-  T_total[!is.infinite(T_total)]

# to check data
summary(NT_t) 
summary(T_t)

#create data (https://www.r-graph-gallery.com/96-boxplot-with-jitter.html) 
data <- data.frame(
  Condition=c( rep("NT",length(NT_t)), rep("TX",length(T_t)) ),
  FRET=c(NT_t,T_t)
)

#box plot with ggplot2 (http://www.sthda.com/english/wiki/ggplot2-box-plot-quick-start-guide-r-software-and-data-visualization)
ggplot(data, aes(x=Condition, y=FRET, color=Condition))  +  geom_boxplot(outlier.shape=NA) +
  coord_cartesian(ylim = c(0, 6)) +
  scale_color_manual(values=c("blue", "red")) 

#t.test
t.test(NT_t,T_t)

dev.off()
par(mfrow=c(4,5))
#par(mfrow=c(2,5))
#heatmap1
t <- NT_3_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_3_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_4_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_4_5
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_6_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_2_3_6_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_2_3_7_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_2_3_7_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_2_4_5_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- NT_2_4_6_3
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_3_3
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_3_6
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_4_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_4_7
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_6_4
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_2_4_6_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_2_4_6_3
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_2_5_1
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_2_5_2
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

#heatmap1
t <- T_2_5_5
t[t >5] <- 5
t<-as.matrix(t)
r = raster(volcano) #raster object
r = raster(t)
cuts=c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)#set breaks
pal <- colorRampPalette(c("blue","green","yellow","red","brown"))
plot(r, breaks=cuts, col = pal(10)) #plot

